language: go
go:
  - 1.7.1
before_install:
  - go get github.com/tools/godep
install:
 - godep restore
script: go test -v ./auth ./channel ./models ./logger # for skipping storage and logger tests for now
