version: '2'
services:
  finch:
    build: .
    ports:
      - "8081:8081"
    volumes:
      - ./config.docker.json:/etc/finch/config.json
  redis:
    image: "redis:3.2.6"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis-data:/data
    entrypoint:
      - redis-server
      - /usr/local/etc/redis/redis.conf
  mongo:
    image: "mongo:3.2.11"
    ports:
      - "27017:27017"
    volumes:
      - "./mongo-data:/data/db"
