version: '2'
services:
  finch:
    build: .
    ports:
      - "8081:8081"
    volumes:
      - ./config.docker.json:/etc/finch/config.json
  redis:
    image: "redis:3.2.6"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis-data:/data
    entrypoint:
      - redis-server
      - /usr/local/etc/redis/redis.conf
  mongo:
    image: "mongo:3.2.11"
    ports:
      - "27017:27017"
    volumes:
      - "./mongo-data:/data/db"
  telegraf:
    image: "telegraf:1.1.2"
    volumes:
      - "./telegraf.conf:/etc/telegraf/telegraf.conf:ro"
    ports:
      - "8125:8125/udp"
  influxdb:
    image: "influxdb:1.1.3"
    volumes:
      - "./influxdb.conf:/etc/influxdb/influxdb.conf:ro"
    ports:
      - "8083:8083"
      - "8086:8086"
  grafana:
    image: "grafana/grafana:4.1.2"
    ports:
      - "3000:3000"
